// Code generated by go-bindata.
// sources:
// schema/node.graphqls
// schema/schema.graphqls
// schema/service.graphqls
// DO NOT EDIT!

package schema

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _schemaNodeGraphqls = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x90\xb1\x6a\xc4\x30\x10\x44\x7b\x7f\xc5\xfa\x37\x54\xc6\x55\x1a\x13\x50\x19\x52\x08\x7b\x6d\x0b\x9c\x5d\xa1\x9d\x18\x42\xc8\xbf\x1f\x58\x2e\xce\x3a\x8e\x3b\xae\xdc\x27\x31\xc3\x9b\x06\xbf\x89\xa9\xd7\x91\xe9\xaf\x21\x22\x1a\x03\x42\xc7\x02\xce\x8e\x3c\x72\x94\xb9\xdd\x79\x4c\xd5\x6d\x9e\xd7\xc9\xd1\x9b\xea\xca\x41\x0a\x94\xf0\xcd\xe7\x6f\x0b\x90\x3e\x34\xc3\xd1\xbb\xa0\xa0\x9c\x86\x8a\x18\xe7\x2d\x0e\x6c\x8e\x3e\x7b\x36\xf8\x72\xb6\x5f\xe5\x51\x42\xf2\x8b\xe2\x9c\x6b\x08\xd8\xab\x02\xb8\x90\x8d\xb3\x45\x95\x23\xf6\xbf\x39\xcc\xd8\x70\x65\x37\xa8\x4c\x71\xbe\x8d\xfa\xb1\x4e\x05\x2c\x55\xcb\xdd\x31\x9e\x93\xaf\x37\x4b\x0f\x87\x78\xd5\xf5\x12\x00\x00\xff\xff\x6a\x44\x02\xfd\xc7\x01\x00\x00")

func schemaNodeGraphqlsBytes() ([]byte, error) {
	return bindataRead(
		_schemaNodeGraphqls,
		"schema/node.graphqls",
	)
}

func schemaNodeGraphqls() (*asset, error) {
	bytes, err := schemaNodeGraphqlsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/node.graphqls", size: 455, mode: os.FileMode(420), modTime: time.Unix(1547182106, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaSchemaGraphqls = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x92\xc1\x6e\x83\x30\x0c\x86\xef\x79\x0a\xf7\x56\xa4\x3d\x41\x6e\xb4\xe5\x50\xa9\xdd\x3a\xc2\x76\x99\x38\x44\x60\x20\xd2\x48\xba\x24\x54\xaa\x26\xde\x7d\x4a\x48\x18\x74\xb7\x9d\xb0\x3f\xfb\x37\xf6\x0f\xa6\xea\xb0\xe7\xf0\x4d\x00\x00\xbe\x06\xd4\x77\x0a\xaf\xee\xe1\x41\x3f\x58\x6e\x85\x92\x14\xce\x21\x22\x23\x21\xf6\x7e\xc5\xa9\x29\xe8\xa4\xaa\x71\x2b\x79\x8f\x14\x98\xd5\x42\xb6\x9b\x84\xc2\xb3\xaa\x71\xae\x1a\x0a\x1f\x0e\x94\x9e\x68\xd1\x34\x14\x72\xd1\x34\x3e\x35\xa8\x6f\xa8\x17\x0a\x07\x44\xf5\x30\xf2\xc9\x58\x6e\x7d\xca\x2d\x26\x14\xd8\xd4\xb4\x14\xb8\xb7\x04\x5c\xce\x8b\xc6\xcd\xc3\xae\xf1\xa4\xd0\xb7\x5d\x48\xcf\xeb\xd2\x51\x5e\x07\xbb\x29\x93\xbf\x95\x70\x05\xb6\xc2\x58\x8c\x83\x3c\x8b\xf7\xfe\x1a\xe6\x8e\x9a\x26\xcd\x0d\x95\x92\x8d\x68\xe7\xc3\x3c\x4f\x28\xec\x94\xfa\x44\x2e\x7d\x3a\xc8\x7f\x4f\x5f\x99\xf6\x38\x7b\x24\x04\xe5\xd0\x4f\x26\x06\x47\xd2\xd3\xf1\x3d\xf3\x11\x7b\x63\x97\x6c\x5f\xf8\xf8\x90\xa5\x87\x50\x3e\xcd\xb2\x7d\x5f\x07\x11\x2b\xd2\xbc\x08\xd1\xcb\xc5\x07\x79\x36\xc1\x68\xbc\xfb\xbe\xa1\xbb\x15\x76\xa7\xb9\xac\xba\xf5\x62\xad\xb0\xac\xe3\x6b\x76\x43\x6d\xfc\x1f\x17\xe1\x48\x7e\x02\x00\x00\xff\xff\xec\xd3\xcb\x82\xa4\x02\x00\x00")

func schemaSchemaGraphqlsBytes() ([]byte, error) {
	return bindataRead(
		_schemaSchemaGraphqls,
		"schema/schema.graphqls",
	)
}

func schemaSchemaGraphqls() (*asset, error) {
	bytes, err := schemaSchemaGraphqlsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/schema.graphqls", size: 676, mode: os.FileMode(420), modTime: time.Unix(1613315642, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _schemaServiceGraphqls = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x94\x90\xb1\x8a\xc3\x30\x0c\x86\x77\x3f\x85\xfc\x1a\x1e\x2f\x53\x86\xcb\x92\xf1\xb8\xc1\xd8\x6a\x30\x34\x92\xb1\xe5\x42\x29\x79\xf7\x92\xb4\x69\x71\x52\x02\x1d\x25\xf3\x7f\xfe\xf4\x07\x8a\x45\xe0\xb7\x88\x95\xc0\xd4\x63\xba\x04\x87\xed\xb2\xbc\x29\x00\x00\x37\x7a\x03\xcd\xe8\xf5\x32\x91\x1d\xd1\x40\x2f\x29\xd0\xf0\xd8\x84\x58\xcf\x91\x93\x18\x68\x49\xb4\x9a\x94\xaa\xf1\x1d\xfb\x8a\x7d\x9c\x95\x6b\x44\xe8\x30\xcb\xd3\x6a\x15\x62\x3a\x85\xa1\x0e\x66\xb1\x52\x72\xc3\x24\x48\x52\x3f\x7d\x65\xbc\xb2\x96\x84\x15\x7c\x7b\xd4\x0e\x7b\x28\xb1\xc7\x6c\xe0\x6f\xf6\x9d\xcf\xd4\xff\xaf\xe8\xa6\xdc\x8f\xbd\x62\x4a\x9c\x8e\x35\xf7\x7f\x6e\xc5\x8b\x73\x98\xb3\x81\x1f\xe6\x33\x5a\xd2\x6a\xba\x07\x00\x00\xff\xff\x10\x57\x4e\xae\xde\x01\x00\x00")

func schemaServiceGraphqlsBytes() ([]byte, error) {
	return bindataRead(
		_schemaServiceGraphqls,
		"schema/service.graphqls",
	)
}

func schemaServiceGraphqls() (*asset, error) {
	bytes, err := schemaServiceGraphqlsBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "schema/service.graphqls", size: 478, mode: os.FileMode(420), modTime: time.Unix(1613315627, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"schema/node.graphqls":    schemaNodeGraphqls,
	"schema/schema.graphqls":  schemaSchemaGraphqls,
	"schema/service.graphqls": schemaServiceGraphqls,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"schema": &bintree{nil, map[string]*bintree{
		"node.graphqls":    &bintree{schemaNodeGraphqls, map[string]*bintree{}},
		"schema.graphqls":  &bintree{schemaSchemaGraphqls, map[string]*bintree{}},
		"service.graphqls": &bintree{schemaServiceGraphqls, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
